{{- if .Values.mcpRunner.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adacor-workplace.mcpRunner.fullname" . }}
  labels:
    {{- include "adacor-workplace.mcpRunner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adacor-workplace.mcpRunner.selectorLabels" . | nindent 4 }}
{{- end }}
