{{- if and .Values.backend.secret.create (not .Values.backend.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adacor-workplace.fullname" . }}
  labels:
    {{- include "adacor-workplace.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.backend.secret.data }}
  {{- if $val }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}
