/**
 * Tests for the Unified Search Service (backend/src/services/searchService.ts)
 *
 * All file system operations, external tools, LLM calls, and path utilities
 * are mocked at the module level so no real disk I/O or network calls occur.
 * Mocks must be registered BEFORE the dynamic import of the module under test.
 */

import { test, expect, describe, mock, beforeEach } from "bun:test";

// ---------------------------------------------------------------------------
// Shared mutable mock state
// ---------------------------------------------------------------------------

const mockState = {
  // Virtual in-memory file system: path -> content
  files: {} as Record<string, string>,
  // Directory contents: path -> list of entry names
  dirs: {} as Record<string, string[]>,

  // Tool registry stubs
  confluenceTool: null as null | { execute: (args: any, ctx: any) => Promise<string> },
  gdriveTool: null as null | { execute: (args: any, ctx: any) => Promise<string> },

  // Memory service stub
  chatSearchResults: [] as any[],
  chatSearchShouldThrow: false,

  // LLM service stub
  llmResponse: { content: '{"relevant_indices":[],"reasoning":"no match"}' } as { content: string },
  llmShouldThrow: false,
};

// Fixed path constants used throughout the tests
const KB_BASE = "/data/knowledge-base";
const APPS_DIR = "/data/apps";

// ---------------------------------------------------------------------------
// Module mocks — declared BEFORE the module under test is imported
// ---------------------------------------------------------------------------

mock.module("fs/promises", () => ({
  readFile: async (path: string, _encoding: string) => {
    if (mockState.files[path] !== undefined) return mockState.files[path];
    const err: any = new Error(`ENOENT: no such file or directory, open '${path}'`);
    err.code = "ENOENT";
    throw err;
  },
  readdir: async (path: string) => {
    if (mockState.dirs[path] !== undefined) return mockState.dirs[path];
    const err: any = new Error(`ENOENT: no such file or directory, scandir '${path}'`);
    err.code = "ENOENT";
    throw err;
  },
}));

mock.module("fs", () => ({
  existsSync: (path: string) =>
    mockState.files[path] !== undefined || mockState.dirs[path] !== undefined,
}));

mock.module("path", () => ({
  join: (...parts: string[]) => parts.join("/"),
}));

mock.module("../../utils/paths", () => ({
  KB_BASE,
  APPS_DIR,
}));

mock.module("../memory", () => ({
  searchChatHistories: async (_query: string) => {
    if (mockState.chatSearchShouldThrow) throw new Error("Memory error");
    return mockState.chatSearchResults;
  },
}));

mock.module("../../tools/registry", () => ({
  toolRegistry: {
    get: (name: string) => {
      if (name === "confluence_search") return mockState.confluenceTool;
      if (name === "gdrive_search") return mockState.gdriveTool;
      return undefined;
    },
  },
}));

// yaml mock — the service does `const { parse } = await import('yaml')`.
// Bun validates named exports against the real module, so we include
// all exports from the real yaml package to avoid SyntaxError at import time.
// Only parse() needs real logic; everything else is a no-op stub.
mock.module("yaml", () => ({
  parse: (content: string) => {
    // Minimal YAML parser that handles the indented key:value format used
    // in contract metadata.yaml files generated by buildContracts().
    const result: Record<string, any> = {};
    const lines = content.split("\n");
    let currentObj: Record<string, any> = result;
    const stack: Array<{ obj: Record<string, any>; indent: number }> = [];

    for (const line of lines) {
      if (line.trim() === "" || line.trim().startsWith("#")) continue;

      const indentMatch = line.match(/^(\s*)/);
      const indent = indentMatch ? indentMatch[1]!.length : 0;
      const trimmed = line.trim();

      // Pop stack back to the appropriate nesting level
      while (stack.length > 0 && indent <= stack[stack.length - 1]!.indent) {
        stack.pop();
        currentObj = stack.length > 0 ? stack[stack.length - 1]!.obj : result;
      }

      const colonIdx = trimmed.indexOf(":");
      if (colonIdx === -1) continue;

      const key = trimmed.slice(0, colonIdx).trim();
      const rawVal = trimmed.slice(colonIdx + 1).trim();

      if (rawVal === "" || rawVal === ">-" || rawVal === "|") {
        // Nested object — push context
        const child: Record<string, any> = {};
        currentObj[key] = child;
        stack.push({ obj: currentObj, indent });
        currentObj = child;
      } else {
        // Scalar — strip surrounding quotes; coerce numbers/booleans
        let val: any = rawVal.replace(/^["']|["']$/g, "");
        if (val !== "" && !isNaN(Number(val))) val = Number(val);
        else if (val === "true") val = true;
        else if (val === "false") val = false;
        currentObj[key] = val;
      }
    }

    return result;
  },
  // Stubs for other yaml exports required to satisfy Bun's module validation
  stringify: (_value: any) => "",
  parseAllDocuments: () => [],
  parseDocument: () => null,
  visit: () => {},
  visitAsync: async () => {},
  // Class stubs
  Composer: class {},
  Document: class {},
  Schema: class {},
  YAMLError: class {},
  YAMLParseError: class {},
  YAMLWarning: class {},
  Alias: class {},
  Pair: class {},
  Scalar: class {},
  YAMLMap: class {},
  YAMLSeq: class {},
  Lexer: class {},
  LineCounter: class {},
  Parser: class {},
  CST: {},
  // identity predicates
  isAlias: () => false,
  isCollection: () => false,
  isDocument: () => false,
  isMap: () => false,
  isNode: () => false,
  isPair: () => false,
  isScalar: () => false,
  isSeq: () => false,
}));

// The service does `await import('./llm')` from within src/services/.
// When mock.module is called from this test (in src/services/__tests__),
// "../llm" resolves to src/services/llm — matching the source file's import.
mock.module("../llm", () => ({
  llmService: {
    chat: async (_messages: any[], _opts?: any, _ctx?: any) => {
      if (mockState.llmShouldThrow) throw new Error("LLM error");
      return mockState.llmResponse;
    },
  },
}));

// ---------------------------------------------------------------------------
// Import module under test AFTER all mocks are registered
// ---------------------------------------------------------------------------

const {
  unifiedSearch,
  smartKnowledgeSearch,
  smartContractSearch,
} = await import("../searchService");

// ---------------------------------------------------------------------------
// Helper builders
// ---------------------------------------------------------------------------

/**
 * Populate the virtual file system with a minimal knowledge base structure.
 *
 * collections.yaml format must match the regex used in searchKnowledgeBase:
 *   /- id: "([^"]+)"\s+name: "([^"]+)"\s+description: "([^"]*)"/g
 *
 * manifest.yaml format must match:
 *   /- document_id: "([^"]+)"\s+title: "([^"]+)"\s+path: "([^"]+)"/g
 */
function buildKnowledgeBase(
  collections: Array<{
    id: string;
    name: string;
    description?: string;
    docs?: Array<{
      docId: string;
      title: string;
      path: string;
      metaContent?: string;
    }>;
  }>
): void {
  // Mark KB base dir as existing
  mockState.dirs[KB_BASE] = collections.map((c) => c.id);

  // Build collections.yaml with format matching the service's regex
  const collectionsYaml = collections
    .map(
      (c) =>
        `- id: "${c.id}"\n  name: "${c.name}"\n  description: "${c.description ?? ""}"`
    )
    .join("\n");
  mockState.files[`${KB_BASE}/collections.yaml`] = collectionsYaml;

  // Build per-collection manifest and DOCUMENT_META.md files
  for (const col of collections) {
    const colDir = `${KB_BASE}/collections/${col.id}`;
    mockState.dirs[colDir] = ["manifest.yaml"];

    const docs = col.docs ?? [];
    // Format must match: /- document_id: "([^"]+)"\s+title: "([^"]+)"\s+path: "([^"]+)"/g
    const manifestYaml = docs
      .map(
        (d) =>
          `- document_id: "${d.docId}"\n  title: "${d.title}"\n  path: "${d.path}"`
      )
      .join("\n");
    mockState.files[`${colDir}/manifest.yaml`] = manifestYaml;

    for (const doc of docs) {
      const docDir = `${colDir}/documents/${doc.path}`;
      mockState.dirs[docDir] = ["DOCUMENT_META.md"];
      mockState.files[`${docDir}/DOCUMENT_META.md`] =
        doc.metaContent ??
        `## Inhaltsbeschreibung\nA default description.\n## Keywords\ndefault, test\n## Beantwortet Fragen zu\nWhat is a test?`;
    }
  }
}

/**
 * Populate the virtual file system with contract data for searchContracts /
 * loadContractsIndex.
 *
 * The YAML format must be parseable by the minimal yaml mock above.
 */
function buildContracts(
  contracts: Array<{
    id: string;
    partyA?: string;
    partyB?: string;
    contractType?: string;
    uploadFilename?: string;
    status?: string;
    annualValue?: number;
    startDate?: string;
    endDate?: string;
    documentContent?: string;
  }>
): void {
  const contractsBase = `${APPS_DIR}/vertragsmanagement/contracts`;
  mockState.dirs[contractsBase] = contracts.map((c) => c.id);

  for (const contract of contracts) {
    const contractDir = `${contractsBase}/${contract.id}`;
    mockState.dirs[contractDir] = ["metadata.yaml"];

    // YAML with computed nested object matching the service's field accesses
    const metaLines = [
      `contract_type: "${contract.contractType ?? ""}"`,
      `upload_filename: "${contract.uploadFilename ?? ""}"`,
      `computed:`,
      `  party_a: "${contract.partyA ?? ""}"`,
      `  party_b: "${contract.partyB ?? ""}"`,
      `  status: "${contract.status ?? ""}"`,
      `  annual_value: ${contract.annualValue ?? 0}`,
      `  start_date: "${contract.startDate ?? ""}"`,
      `  end_date: "${contract.endDate ?? ""}"`,
    ];
    mockState.files[`${contractDir}/metadata.yaml`] = metaLines.join("\n");

    if (contract.documentContent !== undefined) {
      mockState.files[`${contractDir}/document.md`] = contract.documentContent;
    }
  }
}

function resetMockState(): void {
  mockState.files = {};
  mockState.dirs = {};
  mockState.chatSearchResults = [];
  mockState.chatSearchShouldThrow = false;
  mockState.confluenceTool = null;
  mockState.gdriveTool = null;
  mockState.llmResponse = {
    content: '{"relevant_indices":[],"reasoning":"no match"}',
  };
  mockState.llmShouldThrow = false;
}

// ---------------------------------------------------------------------------
// Test suites
// ---------------------------------------------------------------------------

describe("searchService", () => {
  // =========================================================================
  // unifiedSearch()
  // =========================================================================

  describe("unifiedSearch()", () => {
    beforeEach(resetMockState);

    test("should return a response with the original query echoed back", async () => {
      const result = await unifiedSearch("hello world", "user-1");
      expect(result.query).toBe("hello world");
    });

    test("should return empty result arrays when no sources have data", async () => {
      const result = await unifiedSearch("anything", "user-1");
      expect(result.results.chats).toEqual([]);
      expect(result.results.knowledge).toEqual([]);
      expect(result.results.confluence).toEqual([]);
      expect(result.results.gdrive).toEqual([]);
      expect(result.results.contracts).toEqual([]);
    });

    test("should include errors array in the response structure", async () => {
      const result = await unifiedSearch("test", "user-1");
      expect(Array.isArray(result.errors)).toBe(true);
    });

    test("should include chat results when memory service returns matches", async () => {
      mockState.chatSearchResults = [
        {
          id: "chat-1",
          title: "Test Chat",
          snippet: "a snippet",
          matchedIn: "title",
          updatedAt: "2026-01-01T00:00:00.000Z",
        },
      ];
      const result = await unifiedSearch("test", "user-1");
      expect(result.results.chats).toHaveLength(1);
      expect(result.results.chats[0]!.id).toBe("chat-1");
      expect(result.results.chats[0]!.type).toBe("chat");
    });

    test("should include chat title in result", async () => {
      mockState.chatSearchResults = [
        {
          id: "chat-2",
          title: "My Chat Title",
          snippet: "snippet",
          matchedIn: "title",
          updatedAt: "2026-01-01T00:00:00.000Z",
        },
      ];
      const result = await unifiedSearch("chat", "user-1");
      expect(result.results.chats[0]!.title).toBe("My Chat Title");
    });

    test("should map chat metadata fields correctly", async () => {
      mockState.chatSearchResults = [
        {
          id: "chat-3",
          title: "Chat",
          snippet: "text",
          matchedIn: "message",
          updatedAt: "2026-02-01T12:00:00.000Z",
        },
      ];
      const result = await unifiedSearch("test", "user-1");
      const meta = result.results.chats[0]!.metadata;
      expect(meta.matchedIn).toBe("message");
      expect(meta.updatedAt).toBe("2026-02-01T12:00:00.000Z");
    });

    test("should search only the requested sources when sources array is provided", async () => {
      mockState.chatSearchResults = [
        {
          id: "c1",
          title: "T",
          snippet: "s",
          matchedIn: "title",
          updatedAt: "now",
        },
      ];
      const result = await unifiedSearch("query", "user-1", ["chats"]);
      expect(result.results.chats).toHaveLength(1);
      // Knowledge was not requested — returns empty array (not an error)
      expect(result.results.knowledge).toEqual([]);
    });

    test("should skip chats search when 'chats' is not in sources array", async () => {
      mockState.chatSearchResults = [
        {
          id: "c1",
          title: "T",
          snippet: "s",
          matchedIn: "title",
          updatedAt: "now",
        },
      ];
      const result = await unifiedSearch("query", "user-1", ["knowledge"]);
      expect(result.results.chats).toEqual([]);
    });

    test("should include knowledge results when KB has matching documents", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Collection One",
          description: "test collection",
          docs: [
            {
              docId: "doc-1",
              title: "TypeScript Guide",
              path: "ts-guide",
              metaContent:
                "## Inhaltsbeschreibung\nA guide about TypeScript.\n## Keywords\ntypescript, types\n## Beantwortet Fragen zu\nHow to use types?",
            },
          ],
        },
      ]);
      const result = await unifiedSearch("TypeScript", "user-1", ["knowledge"]);
      expect(result.results.knowledge).toHaveLength(1);
      expect(result.results.knowledge[0]!.type).toBe("knowledge");
      expect(result.results.knowledge[0]!.id).toBe("doc-1");
    });

    test("should include contract results when contracts directory has matching data", async () => {
      buildContracts([
        {
          id: "contract-1",
          partyA: "Acme Corp",
          partyB: "Beta GmbH",
          contractType: "Service Agreement",
          uploadFilename: "acme-service.pdf",
          status: "active",
          annualValue: 12000,
          startDate: "2024-01-01",
          endDate: "2025-12-31",
        },
      ]);
      const result = await unifiedSearch("Acme", "user-1", ["contracts"]);
      expect(result.results.contracts).toHaveLength(1);
      expect(result.results.contracts[0]!.type).toBe("contract");
    });

    test("should return results from multiple sources in the same call", async () => {
      mockState.chatSearchResults = [
        {
          id: "c1",
          title: "Chat",
          snippet: "s",
          matchedIn: "title",
          updatedAt: "now",
        },
      ];
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          description: "",
          docs: [
            {
              docId: "doc-1",
              title: "Doc",
              path: "doc-path",
              metaContent:
                "## Inhaltsbeschreibung\ntest\n## Keywords\ntest\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);
      const result = await unifiedSearch("test", "user-1", [
        "chats",
        "knowledge",
      ]);
      expect(result.results.chats).toHaveLength(1);
      expect(result.results.knowledge).toHaveLength(1);
    });

    test("should use all five sources when no sources filter is given", async () => {
      const result = await unifiedSearch("query", "user-1");
      // With default sources, all five result arrays must be present
      expect(result.results).toHaveProperty("chats");
      expect(result.results).toHaveProperty("knowledge");
      expect(result.results).toHaveProperty("confluence");
      expect(result.results).toHaveProperty("gdrive");
      expect(result.results).toHaveProperty("contracts");
    });
  });

  // =========================================================================
  // searchKnowledgeBase (via unifiedSearch with source='knowledge')
  // =========================================================================

  describe("searchKnowledgeBase (via unifiedSearch)", () => {
    beforeEach(resetMockState);

    test("should return empty array when KB_BASE directory does not exist", async () => {
      // dirs is empty, so existsSync(KB_BASE) returns false
      const result = await unifiedSearch("query", "user-1", ["knowledge"]);
      expect(result.results.knowledge).toEqual([]);
    });

    test("should return empty array when collections.yaml does not exist", async () => {
      mockState.dirs[KB_BASE] = []; // KB dir exists but no collections.yaml file
      const result = await unifiedSearch("query", "user-1", ["knowledge"]);
      expect(result.results.knowledge).toEqual([]);
    });

    test("should return empty array when no collections are defined", async () => {
      mockState.dirs[KB_BASE] = [];
      mockState.files[`${KB_BASE}/collections.yaml`] = ""; // empty yaml
      const result = await unifiedSearch("query", "user-1", ["knowledge"]);
      expect(result.results.knowledge).toEqual([]);
    });

    test("should match documents by title (case-insensitive)", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Tech Docs",
          docs: [
            {
              docId: "d1",
              title: "Kubernetes Deployment Guide",
              path: "k8s",
              metaContent:
                "## Inhaltsbeschreibung\nAbout k8s.\n## Keywords\nk8s\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);
      const result = await unifiedSearch("kubernetes", "u1", ["knowledge"]);
      expect(result.results.knowledge).toHaveLength(1);
      expect(result.results.knowledge[0]!.metadata.matchedIn).toBe("title");
    });

    test("should match documents by description", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Tech",
          docs: [
            {
              docId: "d1",
              title: "Unrelated Title",
              path: "p1",
              metaContent:
                "## Inhaltsbeschreibung\nContains Docker information.\n## Keywords\ncontainer\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);
      const result = await unifiedSearch("Docker", "u1", ["knowledge"]);
      expect(result.results.knowledge).toHaveLength(1);
      expect(result.results.knowledge[0]!.metadata.matchedIn).toBe(
        "description"
      );
    });

    test("should match documents by keywords", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          docs: [
            {
              docId: "d1",
              title: "Some Title",
              path: "p1",
              metaContent:
                "## Inhaltsbeschreibung\nGeneric description.\n## Keywords\nterraform, iac, devops\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);
      const result = await unifiedSearch("terraform", "u1", ["knowledge"]);
      expect(result.results.knowledge).toHaveLength(1);
      expect(result.results.knowledge[0]!.metadata.matchedIn).toBe("keywords");
    });

    test("should match documents by questions section", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          docs: [
            {
              docId: "d1",
              title: "Some Title",
              path: "p1",
              metaContent:
                "## Inhaltsbeschreibung\nGeneric.\n## Keywords\nunrelated\n## Beantwortet Fragen zu\nHow do I configure nginx?",
            },
          ],
        },
      ]);
      const result = await unifiedSearch("nginx", "u1", ["knowledge"]);
      expect(result.results.knowledge).toHaveLength(1);
      expect(result.results.knowledge[0]!.metadata.matchedIn).toBe("questions");
    });

    test("should not return documents that do not match the query", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          docs: [
            {
              docId: "d1",
              title: "Spring Boot Setup",
              path: "spring",
              metaContent:
                "## Inhaltsbeschreibung\nJava web framework.\n## Keywords\njava, spring\n## Beantwortet Fragen zu\nHow to build a Java app?",
            },
          ],
        },
      ]);
      const result = await unifiedSearch("python", "u1", ["knowledge"]);
      expect(result.results.knowledge).toHaveLength(0);
    });

    test("should return collectionId, collectionName, and path in metadata", async () => {
      buildKnowledgeBase([
        {
          id: "col-xyz",
          name: "XYZ Collection",
          docs: [
            {
              docId: "doc-abc",
              title: "Matching Doc",
              path: "matching-path",
              metaContent:
                "## Inhaltsbeschreibung\nThis is about matching.\n## Keywords\nmatch\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);
      const result = await unifiedSearch("matching", "u1", ["knowledge"]);
      const meta = result.results.knowledge[0]!.metadata;
      expect(meta.collectionId).toBe("col-xyz");
      expect(meta.collectionName).toBe("XYZ Collection");
      expect(meta.path).toBe("matching-path");
    });

    test("should parse comma-separated keywords into an array", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          docs: [
            {
              docId: "d1",
              title: "Auth Guide",
              path: "auth",
              metaContent:
                "## Inhaltsbeschreibung\nAuthentication details.\n## Keywords\noauth, jwt, tokens\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);
      const result = await unifiedSearch("oauth", "u1", ["knowledge"]);
      const keywords = result.results.knowledge[0]!.metadata.keywords;
      expect(Array.isArray(keywords)).toBe(true);
      expect(keywords).toContain("oauth");
      expect(keywords).toContain("jwt");
      expect(keywords).toContain("tokens");
    });

    test("should set snippet from description, capped at 200 chars", async () => {
      const longDescription = "A".repeat(300);
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          docs: [
            {
              docId: "d1",
              title: "Long Doc",
              path: "long",
              metaContent: `## Inhaltsbeschreibung\n${longDescription}\n## Keywords\nlong\n## Beantwortet Fragen zu\n`,
            },
          ],
        },
      ]);
      const result = await unifiedSearch("long", "u1", ["knowledge"]);
      expect(result.results.knowledge[0]!.snippet!.length).toBeLessThanOrEqual(
        200
      );
    });

    test("should skip a collection when its manifest.yaml does not exist", async () => {
      mockState.dirs[KB_BASE] = ["col-no-manifest"];
      mockState.files[`${KB_BASE}/collections.yaml`] =
        `- id: "col-no-manifest"\n  name: "Missing Manifest"\n  description: ""`;
      // No manifest file — existsSync returns false → collection is skipped

      const result = await unifiedSearch("query", "u1", ["knowledge"]);
      expect(result.results.knowledge).toEqual([]);
    });

    test("should skip a document when its DOCUMENT_META.md does not exist", async () => {
      const colDir = `${KB_BASE}/collections/col-1`;
      mockState.dirs[KB_BASE] = ["col-1"];
      mockState.files[`${KB_BASE}/collections.yaml`] =
        `- id: "col-1"\n  name: "Col"\n  description: ""`;
      mockState.dirs[colDir] = ["manifest.yaml"];
      mockState.files[`${colDir}/manifest.yaml`] =
        `- document_id: "d1"\n  title: "Missing Meta"\n  path: "missing-meta"`;
      // No DOCUMENT_META.md file — existsSync returns false → document is skipped

      const result = await unifiedSearch("missing", "u1", ["knowledge"]);
      expect(result.results.knowledge).toEqual([]);
    });

    test("should match documents across multiple collections", async () => {
      buildKnowledgeBase([
        {
          id: "col-a",
          name: "Collection A",
          docs: [
            {
              docId: "d1",
              title: "Doc about search",
              path: "d1",
              metaContent:
                "## Inhaltsbeschreibung\nSearch indexing.\n## Keywords\nsearch\n## Beantwortet Fragen zu\n",
            },
          ],
        },
        {
          id: "col-b",
          name: "Collection B",
          docs: [
            {
              docId: "d2",
              title: "Another search doc",
              path: "d2",
              metaContent:
                "## Inhaltsbeschreibung\nAlso about search.\n## Keywords\nsearch, index\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);
      const result = await unifiedSearch("search", "u1", ["knowledge"]);
      expect(result.results.knowledge).toHaveLength(2);
    });
  });

  // =========================================================================
  // searchChats (via unifiedSearch with source='chats')
  // =========================================================================

  describe("searchChats (via unifiedSearch)", () => {
    beforeEach(resetMockState);

    test("should return empty array when memory service returns no results", async () => {
      mockState.chatSearchResults = [];
      const result = await unifiedSearch("query", "u1", ["chats"]);
      expect(result.results.chats).toEqual([]);
    });

    test("should return multiple chat results", async () => {
      mockState.chatSearchResults = [
        {
          id: "c1",
          title: "Chat 1",
          snippet: "s1",
          matchedIn: "title",
          updatedAt: "2026-01-01",
        },
        {
          id: "c2",
          title: "Chat 2",
          snippet: "s2",
          matchedIn: "message",
          updatedAt: "2026-01-02",
        },
      ];
      const result = await unifiedSearch("query", "u1", ["chats"]);
      expect(result.results.chats).toHaveLength(2);
    });

    test("should silently return empty array when memory service throws", async () => {
      // searchChats() has an internal try/catch — it logs the error and returns []
      // rather than letting the rejection propagate up.
      mockState.chatSearchShouldThrow = true;
      const result = await unifiedSearch("query", "u1", ["chats"]);
      expect(result.results.chats).toEqual([]);
      // The error is swallowed internally — no entry added to result.errors
      expect(result.errors?.length ?? 0).toBe(0);
    });

    test("should include snippet field from memory service result", async () => {
      mockState.chatSearchResults = [
        {
          id: "c1",
          title: "T",
          snippet: "relevant snippet text",
          matchedIn: "message",
          updatedAt: "now",
        },
      ];
      const result = await unifiedSearch("snippet", "u1", ["chats"]);
      expect(result.results.chats[0]!.snippet).toBe("relevant snippet text");
    });
  });

  // =========================================================================
  // searchConfluence (via unifiedSearch with source='confluence')
  // =========================================================================

  describe("searchConfluence (via unifiedSearch)", () => {
    beforeEach(resetMockState);

    test("should return empty array when confluence_search tool is not registered", async () => {
      mockState.confluenceTool = null;
      const result = await unifiedSearch("query", "u1", ["confluence"]);
      expect(result.results.confluence).toEqual([]);
    });

    test("should return empty array when tool returns an 'Error:' prefix string", async () => {
      mockState.confluenceTool = {
        execute: async () => "Error: not connected",
      };
      const result = await unifiedSearch("query", "u1", ["confluence"]);
      expect(result.results.confluence).toEqual([]);
    });

    test("should return empty array when tool result contains 'Not connected'", async () => {
      mockState.confluenceTool = {
        execute: async () => "Not connected to Confluence",
      };
      const result = await unifiedSearch("query", "u1", ["confluence"]);
      expect(result.results.confluence).toEqual([]);
    });

    test("should return parsed results when tool returns valid markdown", async () => {
      // Must match the regex:
      // /### (.+)\n- \*\*Type\*\*: (.+)\n- \*\*Space\*\*: (.+) \((.+)\)\n- \*\*ID\*\*: (.+)\n(?:- \*\*Last Modified\*\*: (.+)\n)?(?:- \*\*Excerpt\*\*: (.+)\n)?- \*\*URL\*\*: (.+)/g
      const markdown = [
        "### Engineering Wiki",
        "- **Type**: page",
        "- **Space**: Engineering (ENG)",
        "- **ID**: 12345",
        "- **Last Modified**: 2026-01-15",
        "- **Excerpt**: How to deploy services",
        "- **URL**: https://confluence.example.com/pages/12345",
      ].join("\n");

      mockState.confluenceTool = { execute: async () => markdown };
      const result = await unifiedSearch("deploy", "u1", ["confluence"]);
      expect(result.results.confluence).toHaveLength(1);
      expect(result.results.confluence[0]!.id).toBe("12345");
      expect(result.results.confluence[0]!.title).toBe("Engineering Wiki");
      expect(result.results.confluence[0]!.type).toBe("confluence");
    });

    test("should map confluence metadata fields correctly", async () => {
      const markdown = [
        "### API Reference",
        "- **Type**: page",
        "- **Space**: Platform (PLAT)",
        "- **ID**: 99",
        "- **Last Modified**: 2026-02-01",
        "- **Excerpt**: REST API docs",
        "- **URL**: https://conf.example.com/99",
      ].join("\n");

      mockState.confluenceTool = { execute: async () => markdown };
      const result = await unifiedSearch("API", "u1", ["confluence"]);
      const meta = result.results.confluence[0]!.metadata;
      expect(meta.pageType).toBe("page");
      expect(meta.spaceName).toBe("Platform");
      expect(meta.spaceKey).toBe("PLAT");
      expect(meta.url).toBe("https://conf.example.com/99");
    });

    test("should return empty array when no page blocks match in markdown output", async () => {
      mockState.confluenceTool = {
        execute: async () => "Some text without page blocks",
      };
      const result = await unifiedSearch("query", "u1", ["confluence"]);
      expect(result.results.confluence).toEqual([]);
    });

    test("should return empty array when tool throws", async () => {
      mockState.confluenceTool = {
        execute: async () => {
          throw new Error("Network failure");
        },
      };
      const result = await unifiedSearch("query", "u1", ["confluence"]);
      expect(result.results.confluence).toEqual([]);
    });
  });

  // =========================================================================
  // searchGDrive (via unifiedSearch with source='gdrive')
  // =========================================================================

  describe("searchGDrive (via unifiedSearch)", () => {
    beforeEach(resetMockState);

    test("should return empty array when gdrive_search tool is not registered", async () => {
      mockState.gdriveTool = null;
      const result = await unifiedSearch("query", "u1", ["gdrive"]);
      expect(result.results.gdrive).toEqual([]);
    });

    test("should return empty array when tool result contains error field", async () => {
      mockState.gdriveTool = {
        execute: async () =>
          JSON.stringify({ error: "Not authenticated", results: [] }),
      };
      const result = await unifiedSearch("query", "u1", ["gdrive"]);
      expect(result.results.gdrive).toEqual([]);
    });

    test("should return parsed results from valid JSON response", async () => {
      mockState.gdriveTool = {
        execute: async () =>
          JSON.stringify({
            results: [
              {
                id: "file-abc",
                name: "Q1 Report.xlsx",
                type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                size: 102400,
                modified: "2026-01-20T09:00:00Z",
                link: "https://drive.google.com/file/abc",
              },
            ],
          }),
      };
      const result = await unifiedSearch("Q1", "u1", ["gdrive"]);
      expect(result.results.gdrive).toHaveLength(1);
      expect(result.results.gdrive[0]!.id).toBe("file-abc");
      expect(result.results.gdrive[0]!.title).toBe("Q1 Report.xlsx");
      expect(result.results.gdrive[0]!.type).toBe("gdrive");
    });

    test("should map gdrive metadata fields correctly", async () => {
      mockState.gdriveTool = {
        execute: async () =>
          JSON.stringify({
            results: [
              {
                id: "f1",
                name: "Invoice.pdf",
                type: "application/pdf",
                size: 5000,
                modified: "2026-02-10T14:00:00Z",
                link: "https://drive.google.com/file/f1",
              },
            ],
          }),
      };
      const result = await unifiedSearch("invoice", "u1", ["gdrive"]);
      const meta = result.results.gdrive[0]!.metadata;
      expect(meta.mimeType).toBe("application/pdf");
      expect(meta.size).toBe(5000);
      expect(meta.link).toBe("https://drive.google.com/file/f1");
    });

    test("should return empty array when tool result is not valid JSON", async () => {
      mockState.gdriveTool = {
        execute: async () => "NOT JSON",
      };
      const result = await unifiedSearch("query", "u1", ["gdrive"]);
      expect(result.results.gdrive).toEqual([]);
    });

    test("should return empty array when results field is missing from JSON", async () => {
      mockState.gdriveTool = {
        execute: async () => JSON.stringify({ message: "ok" }),
      };
      const result = await unifiedSearch("query", "u1", ["gdrive"]);
      expect(result.results.gdrive).toEqual([]);
    });

    test("should handle empty results array from gdrive", async () => {
      mockState.gdriveTool = {
        execute: async () => JSON.stringify({ results: [] }),
      };
      const result = await unifiedSearch("query", "u1", ["gdrive"]);
      expect(result.results.gdrive).toEqual([]);
    });

    test("should return empty array when tool throws", async () => {
      mockState.gdriveTool = {
        execute: async () => {
          throw new Error("Token expired");
        },
      };
      const result = await unifiedSearch("query", "u1", ["gdrive"]);
      expect(result.results.gdrive).toEqual([]);
    });
  });

  // =========================================================================
  // searchContracts (via unifiedSearch with source='contracts')
  // =========================================================================

  describe("searchContracts (via unifiedSearch)", () => {
    beforeEach(resetMockState);

    test("should return empty array when contracts directory does not exist", async () => {
      const result = await unifiedSearch("query", "u1", ["contracts"]);
      expect(result.results.contracts).toEqual([]);
    });

    test("should return empty array when no contracts match the query", async () => {
      buildContracts([
        {
          id: "c1",
          partyA: "Alpha AG",
          partyB: "Beta GmbH",
          contractType: "Service",
          uploadFilename: "alpha.pdf",
          status: "active",
          annualValue: 5000,
          startDate: "2024-01-01",
          endDate: "2025-12-31",
        },
      ]);
      const result = await unifiedSearch("ZZZ_NOT_FOUND_ZZZ", "u1", [
        "contracts",
      ]);
      expect(result.results.contracts).toEqual([]);
    });

    test("should match contracts by party name partyA", async () => {
      buildContracts([
        {
          id: "c1",
          partyA: "Acme Corp",
          partyB: "Supplier Ltd",
          contractType: "Supply",
          uploadFilename: "acme.pdf",
          status: "active",
          annualValue: 10000,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);
      const result = await unifiedSearch("Acme", "u1", ["contracts"]);
      expect(result.results.contracts).toHaveLength(1);
      expect(result.results.contracts[0]!.metadata.matchedIn).toBe("parties");
    });

    test("should match contracts by party name partyB", async () => {
      buildContracts([
        {
          id: "c2",
          partyA: "Alpha AG",
          partyB: "Omega Services",
          contractType: "IT",
          uploadFilename: "omega.pdf",
          status: "active",
          annualValue: 3000,
          startDate: "2024-06-01",
          endDate: "2025-05-31",
        },
      ]);
      const result = await unifiedSearch("Omega", "u1", ["contracts"]);
      expect(result.results.contracts).toHaveLength(1);
      expect(result.results.contracts[0]!.metadata.matchedIn).toBe("parties");
    });

    test("should match contracts by contract type", async () => {
      buildContracts([
        {
          id: "c3",
          partyA: "X GmbH",
          partyB: "Y AG",
          contractType: "Wartungsvertrag",
          uploadFilename: "wartung.pdf",
          status: "active",
          annualValue: 2400,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);
      const result = await unifiedSearch("Wartung", "u1", ["contracts"]);
      expect(result.results.contracts).toHaveLength(1);
      expect(result.results.contracts[0]!.metadata.matchedIn).toBe("type");
    });

    test("should match contracts by filename", async () => {
      buildContracts([
        {
          id: "c4",
          partyA: "Corp A",
          partyB: "Corp B",
          contractType: "Lease",
          uploadFilename: "lease-agreement-2024.pdf",
          status: "active",
          annualValue: 1200,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);
      const result = await unifiedSearch("lease-agreement", "u1", [
        "contracts",
      ]);
      expect(result.results.contracts).toHaveLength(1);
      expect(result.results.contracts[0]!.metadata.matchedIn).toBe("filename");
    });

    test("should match contracts by document content and include snippet", async () => {
      buildContracts([
        {
          id: "c5",
          partyA: "Corp A",
          partyB: "Corp B",
          contractType: "NDA",
          uploadFilename: "nda.pdf",
          status: "active",
          annualValue: 0,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
          documentContent:
            "This non-disclosure agreement covers confidential information.",
        },
      ]);
      const result = await unifiedSearch("confidential", "u1", ["contracts"]);
      expect(result.results.contracts).toHaveLength(1);
      expect(result.results.contracts[0]!.metadata.matchedIn).toBe("content");
      expect(result.results.contracts[0]!.snippet).toContain("confidential");
    });

    test("should set contract title to 'partyA - partyB'", async () => {
      buildContracts([
        {
          id: "c6",
          partyA: "Alpha AG",
          partyB: "Beta GmbH",
          contractType: "Service",
          uploadFilename: "service.pdf",
          status: "active",
          annualValue: 5000,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);
      const result = await unifiedSearch("Alpha", "u1", ["contracts"]);
      expect(result.results.contracts[0]!.title).toBe("Alpha AG - Beta GmbH");
    });

    test("should include all required metadata fields in contract results", async () => {
      buildContracts([
        {
          id: "c7",
          partyA: "X",
          partyB: "Y",
          contractType: "Rent",
          uploadFilename: "rent.pdf",
          status: "active",
          annualValue: 1200,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);
      const result = await unifiedSearch("Rent", "u1", ["contracts"]);
      const meta = result.results.contracts[0]!.metadata;
      expect(meta).toHaveProperty("contract_type");
      expect(meta).toHaveProperty("filename");
      expect(meta).toHaveProperty("status");
      expect(meta).toHaveProperty("annual_value");
      expect(meta).toHaveProperty("start_date");
      expect(meta).toHaveProperty("end_date");
      expect(meta).toHaveProperty("matchedIn");
    });

    test("should skip contract directories without metadata.yaml", async () => {
      const contractsBase = `${APPS_DIR}/vertragsmanagement/contracts`;
      mockState.dirs[contractsBase] = ["no-meta-contract"];
      // No metadata.yaml file added → existsSync returns false → contract skipped

      const result = await unifiedSearch("query", "u1", ["contracts"]);
      expect(result.results.contracts).toEqual([]);
    });

    test("should return multiple matching contracts", async () => {
      buildContracts([
        {
          id: "c1",
          partyA: "Berlin Services GmbH",
          partyB: "Muster AG",
          contractType: "Service",
          uploadFilename: "s1.pdf",
          status: "active",
          annualValue: 1000,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
        {
          id: "c2",
          partyA: "Muster AG",
          partyB: "Frankfurt Corp",
          contractType: "IT",
          uploadFilename: "it.pdf",
          status: "active",
          annualValue: 2000,
          startDate: "2024-03-01",
          endDate: "2025-02-28",
        },
      ]);
      const result = await unifiedSearch("Muster", "u1", ["contracts"]);
      expect(result.results.contracts).toHaveLength(2);
    });

    test("should produce a content snippet that includes the query term", async () => {
      buildContracts([
        {
          id: "c8",
          partyA: "A",
          partyB: "B",
          contractType: "NDX",
          uploadFilename: "ndx.pdf",
          status: "active",
          annualValue: 0,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
          documentContent:
            "Lorem ipsum. The penalty clause is defined in section 5.",
        },
      ]);
      const result = await unifiedSearch("penalty clause", "u1", ["contracts"]);
      expect(result.results.contracts[0]!.snippet).toBeDefined();
      expect(result.results.contracts[0]!.snippet).toContain("penalty clause");
    });

    test("should not include snippet when match is only in parties and no document content", async () => {
      buildContracts([
        {
          id: "c9",
          partyA: "Acme Corp",
          partyB: "Other Inc",
          contractType: "Service",
          uploadFilename: "s.pdf",
          status: "active",
          annualValue: 0,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
          // no documentContent
        },
      ]);
      const result = await unifiedSearch("Acme", "u1", ["contracts"]);
      // snippet should be undefined since content match didn't happen
      expect(result.results.contracts[0]!.snippet).toBeUndefined();
    });
  });

  // =========================================================================
  // smartKnowledgeSearch()
  // =========================================================================

  describe("smartKnowledgeSearch()", () => {
    beforeEach(resetMockState);

    test("should return query in response", async () => {
      const result = await smartKnowledgeSearch("test query");
      expect(result.query).toBe("test query");
    });

    test("should return empty results when KB_BASE does not exist", async () => {
      const result = await smartKnowledgeSearch("query");
      expect(result.results).toEqual([]);
      expect(result.reasoning).toContain("nicht gefunden");
    });

    test("should return empty results when KB has no documents", async () => {
      mockState.dirs[KB_BASE] = [];
      mockState.files[`${KB_BASE}/collections.yaml`] = "";
      const result = await smartKnowledgeSearch("query");
      expect(result.results).toEqual([]);
    });

    test("should call LLM and return results for matching indices", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Tech",
          docs: [
            {
              docId: "doc-1",
              title: "React Guide",
              path: "react",
              metaContent:
                "## Inhaltsbeschreibung\nFrontend framework.\n## Keywords\nreact, frontend\n## Beantwortet Fragen zu\nHow to build UIs?",
            },
          ],
        },
      ]);

      mockState.llmResponse = {
        content:
          '{"relevant_indices":[0],"reasoning":"React is relevant to the query"}',
      };

      const result = await smartKnowledgeSearch("react ui");
      expect(result.results).toHaveLength(1);
      expect(result.results[0]!.id).toBe("doc-1");
      expect(result.results[0]!.type).toBe("knowledge");
      expect(result.reasoning).toBe("React is relevant to the query");
    });

    test("should return empty results when LLM responds with empty indices", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Tech",
          docs: [
            {
              docId: "doc-1",
              title: "Doc",
              path: "d1",
              metaContent:
                "## Inhaltsbeschreibung\nContent.\n## Keywords\nkey\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);

      mockState.llmResponse = {
        content: '{"relevant_indices":[],"reasoning":"nothing relevant"}',
      };

      const result = await smartKnowledgeSearch("unrelated query");
      expect(result.results).toEqual([]);
    });

    test("should handle LLM response wrapped in JSON code block", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          docs: [
            {
              docId: "d1",
              title: "Doc",
              path: "p1",
              metaContent:
                "## Inhaltsbeschreibung\nContent.\n## Keywords\nk\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);

      mockState.llmResponse = {
        content:
          "```json\n{\"relevant_indices\":[0],\"reasoning\":\"found it\"}\n```",
      };

      const result = await smartKnowledgeSearch("query");
      expect(result.results).toHaveLength(1);
    });

    test("should filter out invalid out-of-bounds indices from LLM response", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          docs: [
            {
              docId: "d1",
              title: "Only Doc",
              path: "p1",
              metaContent:
                "## Inhaltsbeschreibung\nSingle doc.\n## Keywords\nonly\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);

      // LLM returns index 0 (valid) and 99 (out of bounds)
      mockState.llmResponse = {
        content: '{"relevant_indices":[0,99],"reasoning":"found some"}',
      };

      const result = await smartKnowledgeSearch("only");
      expect(result.results).toHaveLength(1);
      expect(result.results[0]!.id).toBe("d1");
    });

    test("should return error reasoning when LLM response contains no JSON object", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          docs: [
            {
              docId: "d1",
              title: "Doc",
              path: "p1",
              metaContent:
                "## Inhaltsbeschreibung\nContent.\n## Keywords\nk\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);

      mockState.llmResponse = { content: "I cannot help with that." };
      const result = await smartKnowledgeSearch("query");
      expect(result.results).toEqual([]);
      expect(result.reasoning).toContain("Fehler");
    });

    test("should return error reasoning when LLM throws", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          docs: [
            {
              docId: "d1",
              title: "Doc",
              path: "p1",
              metaContent:
                "## Inhaltsbeschreibung\nContent.\n## Keywords\nk\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);

      mockState.llmShouldThrow = true;
      const result = await smartKnowledgeSearch("query");
      expect(result.results).toEqual([]);
      expect(result.reasoning).toContain("Fehler");
    });

    test("should set matchedIn='smart_search' in result metadata", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          docs: [
            {
              docId: "d1",
              title: "Doc",
              path: "p1",
              metaContent:
                "## Inhaltsbeschreibung\nAbout AI.\n## Keywords\nai\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);

      mockState.llmResponse = {
        content: '{"relevant_indices":[0],"reasoning":"ai match"}',
      };

      const result = await smartKnowledgeSearch("ai");
      expect(result.results[0]!.metadata.matchedIn).toBe("smart_search");
    });

    test("should set snippet from document description in smart results", async () => {
      buildKnowledgeBase([
        {
          id: "col-1",
          name: "Col",
          docs: [
            {
              docId: "d1",
              title: "Doc",
              path: "p1",
              metaContent:
                "## Inhaltsbeschreibung\nDetailed description of the document.\n## Keywords\nk\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);

      mockState.llmResponse = {
        content: '{"relevant_indices":[0],"reasoning":"match"}',
      };

      const result = await smartKnowledgeSearch("document");
      expect(result.results[0]!.snippet).toContain("Detailed description");
    });

    test("should include collectionId and collectionName in metadata", async () => {
      buildKnowledgeBase([
        {
          id: "col-smart",
          name: "Smart Collection",
          docs: [
            {
              docId: "d-smart",
              title: "Smart Doc",
              path: "smart",
              metaContent:
                "## Inhaltsbeschreibung\nSmart content.\n## Keywords\nsmart\n## Beantwortet Fragen zu\n",
            },
          ],
        },
      ]);

      mockState.llmResponse = {
        content: '{"relevant_indices":[0],"reasoning":"match"}',
      };

      const result = await smartKnowledgeSearch("smart");
      const meta = result.results[0]!.metadata;
      expect(meta.collectionId).toBe("col-smart");
      expect(meta.collectionName).toBe("Smart Collection");
    });
  });

  // =========================================================================
  // smartContractSearch()
  // =========================================================================

  describe("smartContractSearch()", () => {
    beforeEach(resetMockState);

    test("should return query in response", async () => {
      const result = await smartContractSearch("test query");
      expect(result.query).toBe("test query");
    });

    test("should return empty results when contracts directory does not exist", async () => {
      const result = await smartContractSearch("query");
      expect(result.results).toEqual([]);
      expect(result.reasoning).toContain("vorhanden");
    });

    test("should return empty results when no contracts exist in directory", async () => {
      const contractsBase = `${APPS_DIR}/vertragsmanagement/contracts`;
      mockState.dirs[contractsBase] = []; // Directory exists but empty
      const result = await smartContractSearch("query");
      expect(result.results).toEqual([]);
    });

    test("should call LLM and return results for matching indices", async () => {
      buildContracts([
        {
          id: "ct-1",
          partyA: "Alpha Corp",
          partyB: "Beta GmbH",
          contractType: "Service Agreement",
          uploadFilename: "service.pdf",
          status: "active",
          annualValue: 12000,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);

      mockState.llmResponse = {
        content:
          '{"relevant_indices":[0],"reasoning":"Alpha Corp matches the query"}',
      };

      const result = await smartContractSearch("Alpha");
      expect(result.results).toHaveLength(1);
      expect(result.results[0]!.id).toBe("ct-1");
      expect(result.results[0]!.type).toBe("contract");
      expect(result.reasoning).toBe("Alpha Corp matches the query");
    });

    test("should return empty results when LLM responds with empty indices", async () => {
      buildContracts([
        {
          id: "ct-1",
          partyA: "X",
          partyB: "Y",
          contractType: "NDA",
          uploadFilename: "nda.pdf",
          status: "active",
          annualValue: 0,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);

      mockState.llmResponse = {
        content: '{"relevant_indices":[],"reasoning":"no contracts relevant"}',
      };

      const result = await smartContractSearch("unrelated");
      expect(result.results).toEqual([]);
    });

    test("should handle LLM response wrapped in a JSON code block", async () => {
      buildContracts([
        {
          id: "ct-1",
          partyA: "X",
          partyB: "Y",
          contractType: "T",
          uploadFilename: "f.pdf",
          status: "active",
          annualValue: 0,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);

      mockState.llmResponse = {
        content:
          "```json\n{\"relevant_indices\":[0],\"reasoning\":\"found\"}\n```",
      };

      const result = await smartContractSearch("X");
      expect(result.results).toHaveLength(1);
    });

    test("should filter out invalid out-of-bounds indices", async () => {
      buildContracts([
        {
          id: "ct-1",
          partyA: "Solo",
          partyB: "Corp",
          contractType: "Service",
          uploadFilename: "s.pdf",
          status: "active",
          annualValue: 1000,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);

      // LLM returns index 0 (valid) and 50 (out of bounds)
      mockState.llmResponse = {
        content: '{"relevant_indices":[0,50],"reasoning":"partial"}',
      };

      const result = await smartContractSearch("Solo");
      expect(result.results).toHaveLength(1);
    });

    test("should return error reasoning when LLM response contains no JSON object", async () => {
      buildContracts([
        {
          id: "ct-1",
          partyA: "X",
          partyB: "Y",
          contractType: "T",
          uploadFilename: "f.pdf",
          status: "active",
          annualValue: 0,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);

      mockState.llmResponse = { content: "Unable to process." };
      const result = await smartContractSearch("query");
      expect(result.results).toEqual([]);
      expect(result.reasoning).toContain("Fehler");
    });

    test("should return error reasoning when LLM throws", async () => {
      buildContracts([
        {
          id: "ct-1",
          partyA: "X",
          partyB: "Y",
          contractType: "T",
          uploadFilename: "f.pdf",
          status: "active",
          annualValue: 0,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);

      mockState.llmShouldThrow = true;
      const result = await smartContractSearch("query");
      expect(result.results).toEqual([]);
      expect(result.reasoning).toContain("Fehler");
    });

    test("should set type='contract' on all smart results", async () => {
      buildContracts([
        {
          id: "ct-1",
          partyA: "X",
          partyB: "Y",
          contractType: "Service",
          uploadFilename: "s.pdf",
          status: "active",
          annualValue: 1000,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);

      mockState.llmResponse = {
        content: '{"relevant_indices":[0],"reasoning":"match"}',
      };

      const result = await smartContractSearch("X");
      expect(result.results[0]!.type).toBe("contract");
    });

    test("should set matchedIn='smart_search' in result metadata", async () => {
      buildContracts([
        {
          id: "ct-1",
          partyA: "X",
          partyB: "Y",
          contractType: "Service",
          uploadFilename: "s.pdf",
          status: "active",
          annualValue: 1000,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);

      mockState.llmResponse = {
        content: '{"relevant_indices":[0],"reasoning":"match"}',
      };

      const result = await smartContractSearch("X");
      expect(result.results[0]!.metadata.matchedIn).toBe("smart_search");
    });

    test("should set title to 'partyA - partyB' in smart results", async () => {
      buildContracts([
        {
          id: "ct-1",
          partyA: "Sunset AG",
          partyB: "Horizon GmbH",
          contractType: "Lease",
          uploadFilename: "lease.pdf",
          status: "active",
          annualValue: 6000,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);

      mockState.llmResponse = {
        content: '{"relevant_indices":[0],"reasoning":"found"}',
      };

      const result = await smartContractSearch("Sunset");
      expect(result.results[0]!.title).toBe("Sunset AG - Horizon GmbH");
    });

    test("should include contract_type in snippet", async () => {
      buildContracts([
        {
          id: "ct-1",
          partyA: "A",
          partyB: "B",
          contractType: "Mietvertrag",
          uploadFilename: "miet.pdf",
          status: "active",
          annualValue: 2400,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);

      mockState.llmResponse = {
        content: '{"relevant_indices":[0],"reasoning":"match"}',
      };

      const result = await smartContractSearch("Miet");
      expect(result.results[0]!.snippet).toContain("Mietvertrag");
    });

    test("should include all required metadata fields in smart contract results", async () => {
      buildContracts([
        {
          id: "ct-meta",
          partyA: "Meta A",
          partyB: "Meta B",
          contractType: "Consulting",
          uploadFilename: "consulting.pdf",
          status: "active",
          annualValue: 50000,
          startDate: "2024-01-01",
          endDate: "2024-12-31",
        },
      ]);

      mockState.llmResponse = {
        content: '{"relevant_indices":[0],"reasoning":"match"}',
      };

      const result = await smartContractSearch("Meta");
      const meta = result.results[0]!.metadata;
      expect(meta).toHaveProperty("contract_type");
      expect(meta).toHaveProperty("filename");
      expect(meta).toHaveProperty("status");
      expect(meta).toHaveProperty("annual_value");
      expect(meta).toHaveProperty("start_date");
      expect(meta).toHaveProperty("end_date");
      expect(meta).toHaveProperty("matchedIn");
    });
  });
});
